### ISSUE TITLE
pyrtfolio forces installation of pandas 0.25.3

### ISSUE THREAD

**Issue by typhoon71** [alvarob96/investpy_portfolio#5]
When installing pyrtfolio pandas 0.25.3 will be installed, even if there's already pandas 1.0.4 installed.

I think this should be fixed.

**Comment by alvarobartt** [comment]
Hi again @typhoon71! As I already told you, please fork the repo and make all the changes that you need to and then open a pull request so that I can apply them all into the stable master branch of pyrtfolio. Thank you!

**Comment by typhoon71** [comment]
Done. I made 2 pull request, since there's also `investpy==0.9.14` but I don't know if there's a reason for it to be locked.

**Comment by alvarobartt** [comment]
No, there is no reason for investpy to be limited to the 0.9.14 version. Also you need to create the pull request to the master branch, since you created the pull requests into your own fork.

**Comment by typhoon71** [comment]
Will do, I knew I'd do it wrong.

**Comment by typhoon71** [comment]
Now?

**Comment by alvarobartt** [comment]
Steps: `New Pull request` at https://github.com/alvarobartt/pyrtfolio/pulls -> `Compare across forks` -> Select your fork -> Describe all the feature, fixes, etc that you solved within your fork

**Comment by alvarobartt** [comment]
No, check the steps I just mentioned you! Thank you!

**Comment by typhoon71** [comment]
Should I choose master or developer?

**Comment by alvarobartt** [comment]
developer
